language: python

python:
  - "3.6"

env:
  - DJANGO=2.0 DB=postgres

dist: xenial

install:
  - pip install -r requirements.txt
  - pip install codacy-coverage
  - python -m pip install flake8 
services:
  - postgresql

addons:
  postgresql: "9.4"

global:
  - PGPORT=5432

before_script:
  - psql -U postgres -c "create user decide password 'decide'"
  - psql -U postgres -c "create database decide_db owner decide"
  - psql -U postgres -c "ALTER USER decide CREATEDB"

script:  
  - cd decide 
  - cp travis_local_settings.py local_settings.py
  - coverage run --branch --source=. ./manage.py test --keepdb --with-xunit
  - coverage xml
  - python-codacy-coverage -r coverage.xml
  - python3.6 -m flake8 . 
