language: python

python:
  - "3.6"

env:
  - DJANGO=2.0 DB=postgres

dist: xenial

install:
  - pip install -r requirements.txt
  
services:
  - postgresql

addons:
  postgresql: "9.4"

global:
  - PGPORT=5432

before_script:
  - cp travis_local_settings.py local_settings.py
  - psql -U postgres -c "create user decide password 'decide'"
  - psql -U postgres -c "create database test_decide owner decide"
  - psql -U postgres -c "ALTER USER decide CREATEDB"
  - python manage.py migrate

script:
  - cd decide
  - python manage.py test
